# MD007
ul-indent:
  indent: 4

# MD013
line-length:
  line_length: 80

# MD024
no-duplicate-heading:
  siblings_only: true

# MD025
single-title:
  front_matter_title: ""

# MD033
no-inline-html:
  allowed_elements:
    - img
