theme:
  # current playing song in list (Cyan)
  active: Green
  # the "spotify-tui" banner on launch (LightCyan)
  banner: LightGreen

  # error dialog border (Red)
  error_border: Red
  # error message text (LightRed)
  error_text: LightRed
  # error hint text (Yellow)
  hint: Yellow

  # hovered pane border (Magenta)
  hovered: White
  # borders of inactive panes (Gray)
  inactive: Gray

  # background of progress bar (Black)
  playbar_background: Black
  # filled-in part of the progress bar (LightCyan)
  playbar_progress: Gray
  # artist name in player pane (White)
  playbar_text: Gray
  # selected pane border, hovered item in list, track title in player (LightCyan)
  selected: LightGreen
  # text in panes ("255, 255, 255")
  text: Gray

behavior:
  # milliseconds to seek at a time (5000)
  seek_milliseconds: 10000
  # % to increase/decrease the volume at a time (10)
  volume_increment: 5
  # audio visualisation update interval (250)
  tick_rate_milliseconds: 125
  # show an indicator in the top right when communicating with Spotify (true)
  show_loading_indicator: false
